image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - eventyret.bootstrap-4-cdn-snippet@1.6.0:AtNd6GnbCYVpmUkOaFXs3A==
    - esbenp.prettier-vscode@4.3.0:jkl8NYpF/GzsahVpjggK0Q==
    - kevinglasson.cornflakes-linter@0.4.0:Sgfmpf9YWoF5/BDJu2xn0w==

FROM gitpod/workspace-full
USER gitpod
RUN sudo apt-get update -q && \
    sudo aptitude install gdal-bin libgdal-dev
    sudo aptitude install python3-gdal
    sudo aptitude install binutils libproj-dev
    docker run --name=postgis -d -e POSTGRES_USER=user999 -e POSTGRES_PASS=123456789 -e POSTGRES_DBNAME=gis -p 5432:5432 kartoza/postgis:9.6-2.4